extends: stylelint-config-standard
plugins:
  stylelint-scss
rules:
  at-rule-empty-line-before: null
  at-rule-name-space-after: always
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - else
      - error
      - forward
      - function
      - if
      - include
      - mixin
      - return
      - use
  block-closing-brace-newline-after:
    - always
    - ignoreAtRules:
      - else
      - if
  block-opening-brace-space-before: always
  color-hex-length: long
  color-hex-case: lower
  comment-empty-line-before:
    - always
  selector-pseudo-element-colon-notation: null
  scss/at-else-closing-brace-newline-after: always-last-in-chain
  scss/at-else-closing-brace-space-after: always-intermediate
  scss/at-else-empty-line-before: never
  scss/at-if-closing-brace-newline-after: always-last-in-chain
  scss/at-if-closing-brace-space-after: always-intermediate
