name: Run tests

on:
 - push

jobs:
  localisation-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"
        cache: npm
    - run: npm ci --include=optional
    - run: ELEVENTY_PLACEHOLDER=true npm run build # Build using placeholder content
    - run: npm run test:runner # Run test set for running in this workflow
